/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_khpi_oop_lab16_NativeNormalizer */

#ifndef _Included_ua_khpi_oop_lab16_NativeNormalizer
#define _Included_ua_khpi_oop_lab16_NativeNormalizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_khpi_oop_lab16_NativeNormalizer
 * Method:    normalize
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ua_khpi_oop_lab16_NativeNormalizer_normalize
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
